name: UPDATE OFFICIAL REPO MANIFEST URL ACTION

on:
  workflow_dispatch:
  schedule:
    - cron: '16 21 * * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x scripts/update.sh
      - name: update-url
        run: ./scripts/update.sh
        continue-on-error: true
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

