# This is a basic workflow to help you get started with Actions

name: UPDATE MANIFEST URL ACTION

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '30 5 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: download manifest
        run: wget https://mirrors.nju.edu.cn/jellyfin/files/plugin/manifest.json

      - name: update url in manifest
        run: sed -i 's_https://repo.jellyfin.org_https://mirrors.nju.edu.cn/jellyfin_' manifest.json

      - name: commit
        id: commit
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"
          git add manifest.json
          git commit -m "update manifest.json"
        continue-on-error: true
      - name: Check on failure
        if: steps.commit.outputs.status == 'failure'
        run: exit 1
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Cache src repos
      uses: actions/cache@v2.1.3
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
        restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

      - name: Mirror to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/kk77mgj
          dst: gitee/zjwzcntzy
          dst_key: ${{ secrets.SSH_PRIVATE_TOKEN }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          static_list: "Jellyfin-Plugins-NJU-Mirror"
          cache_path: /github/workspace/hub-mirror-cache
          force_update: true


